Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,8 +16,12 @@ jobs:
     - uses: actions/checkout@v3
     - name: Build the Docker images changed
       run: |
-        for FILE in $(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep -i "Dockerfile")
+        for FILE in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -i "Dockerfile")
         do
           TEMP_IMAGE_NAME="img-$RANDOM"
-          docker build {{ github.workspace	}} --file $FILE -t $TEMP_IMAGE_NAME
-        done;
+          docker build {{ github.workspace }} --file $FILE -t $TEMP_IMAGE_NAME
+          if [ $? -ne 0 ] 
+          then 
+            echo "Error building image for: $FILE"
+            exit 1
+          fi
